# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d3b58b80e0b4bd45fe204b17a15e71c5aee2153230c3bff6ff867d73aca7a2ca3e0be1c5db0f0bed96ef3dc48d85c5703e36a0778e419d140c2ef1920493904

test:
  secret_key_base: bd083b49f82c7728a2cd5ccec9dd59530e6fac6cf0d3afe2a5982ba52bca1be54444831cf70d963bbda48186ed5b7809712b5128dcab6d30c94bc5d129168b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
